export const theme = {
  colors: {
    primary: '#1877f2',
    secondary: '#42a5f5',
    accent: '#e3f2fd',
    background: '#f0f2f5',
    surface: '#ffffff',
    text: '#1c1e21',
    textSecondary: '#65676b',
    playerX: '#e74c3c',
    playerO: '#3498db',
    win: '#42b883',
    tie: '#f39c12',
    border: '#dadde1',
    gridBackground: '#ffffff',
    cardShadow: 'rgba(0, 0, 0, 0.1)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
  },
  typography: {
    h1: 28,
    h2: 24,
    h3: 20,
    body: 16,
    caption: 14,
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    button: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
    },
  },
};